on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install dependencies and build
        run: yarn && yarn build
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1       
        with:
          username: 'irina'
          server: 'debank.etna.network'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './public/*'
          remote_path: '/home/irina/frontend/new-etna-debank/'
          args: '-o ConnectTimeout=5'
