on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# https://docs.github.com/en/actions/guides/building-and-testing-nodejs

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies and build
        run: yarn && yarn build:prod
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1       
        with:
          username: 'irina'
          server: 'preprod-debank.etna.network'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './public/*'
          remote_path: '/home/irina/frontend/preprod-debank/'
          args: '-o ConnectTimeout=5'
