on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# https://docs.github.com/en/actions/guides/building-and-testing-nodejs

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies and build
        run: yarn && yarn build:prod:mobile
      - name: Clear old js/css files
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: '(rm -rf /home/irina/frontend/m-preprod-debank/css/; rm -rf /home/irina/frontend/m-preprod-debank/js/)'
          host: 'm-preprod-debank.etna.network'
          username: 'irina'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1       
        with:
          username: 'irina'
          server: 'm-preprod-debank.etna.network'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './public/*'
          remote_path: '/home/irina/frontend/m-preprod-debank/'
          args: '-o ConnectTimeout=5'
