on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# https://docs.github.com/en/actions/guides/building-and-testing-nodejs

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clear old js/css files
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: ls -a
          host: dev-new-debank.etna.network
          username: Irina
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }} 